import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright-core');
const browser=await chromium.launch({channel:'msedge',headless:true});
const context=await browser.newContext({viewport:{width:390,height:844}});
const page=await context.newPage();
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const pass=message=>console.log(`PASS ${message}`);
try{
 await context.route('**/config.js',route=>route.fulfill({contentType:'application/javascript',body:'window.PANTRY_CONFIG = {};'}));
 await page.goto('http://localhost:4173');
 await page.getByRole('button',{name:'Try sample pantry'}).click();
 await page.getByRole('heading',{name:'Avocados',exact:true}).waitFor();
 assert.equal(await page.locator('.card').count(),5);pass('sample pantry and category groups render');
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);pass('390px layout has no horizontal overflow');
 await page.getByLabel('Food category').selectOption('Fruit');assert.equal(await page.locator('.card').count(),2);
 await page.getByLabel('Search food').fill('blue');assert.equal(await page.locator('.card').count(),1);pass('category filter composes with search');
 await page.getByLabel('Search food').fill('');await page.getByLabel('Food category').selectOption('all');
 let card=page.locator('.card').filter({has:page.getByRole('heading',{name:'Avocados',exact:true})});
 await card.getByRole('button',{name:'Update Avocados batch'}).click();await page.locator('input[name="quantity"]').fill('0');await page.getByRole('button',{name:'Save update',exact:true}).click();await page.locator('dialog').waitFor({state:'hidden'});
 assert.match(await card.innerText(),/Out of stock/);pass('check-in sets remaining quantity; out-of-stock food stays visible');
 await page.reload();card=page.locator('.card').filter({has:page.getByRole('heading',{name:'Avocados',exact:true})});await card.waitFor();assert.match(await card.innerText(),/Out of stock/);pass('stock persists across reload');
 await card.getByRole('button',{name:'To list'}).click();await page.getByRole('button',{name:/Shopping list/}).click();
 let row=page.locator('.shopping-row').filter({has:page.getByRole('heading',{name:'Avocados',exact:true})});await row.getByRole('button',{name:'Restock',exact:true}).click();await page.locator('input[name="quantity"]').fill('4');await page.getByRole('button',{name:'Add to pantry',exact:true}).click();await page.locator('dialog').waitFor({state:'hidden'});assert.equal(await page.locator('.shopping-row').filter({has:page.getByRole('heading',{name:'Avocados',exact:true})}).count(),0);pass('restock completes shopping item');
 await page.getByRole('button',{name:'My inventory'}).click();card=page.locator('.card').filter({has:page.getByRole('heading',{name:'Avocados',exact:true})});assert.match(await card.locator('.amount').innerText(),/4 items/);pass('restock adds quantity once');
 await card.getByRole('button',{name:'Settings for Avocados'}).click();await page.locator('[name="category"]').fill('Breakfast');await page.getByRole('button',{name:'Save settings'}).click();await page.locator('dialog').waitFor({state:'hidden'});await page.getByLabel('Food category').selectOption('Breakfast');assert.equal(await page.locator('.card').count(),1);pass('custom category reassignment');
 await page.getByRole('button',{name:'Add food',exact:false}).click();await page.locator('[name="name"]').fill('Rice');await page.locator('[name="quantity"]').selectOption('0.5');await page.getByRole('button',{name:'Add food',exact:true}).click();await page.locator('dialog').waitFor({state:'hidden'});await page.getByLabel('Food category').selectOption('all');assert.match(await page.locator('.card').filter({has:page.getByRole('heading',{name:'Rice',exact:true})}).innerText(),/Half/);pass('new food defaults to rough levels');
 const before=await page.evaluate(()=>JSON.parse(localStorage.getItem('pantry-organizer.demo.v1')).state);
 await page.getByRole('button',{name:'Restock several',exact:true}).click();
 const rice=page.locator('.bulk-item').filter({has:page.getByRole('checkbox',{name:'Rice Other',exact:true})});await rice.getByRole('checkbox').check();await rice.locator('select[name^="quantity-"]').selectOption('1');
 const avocado=page.locator('.bulk-item').filter({hasText:'Avocados'});await avocado.getByRole('checkbox').check();await avocado.locator('input[name^="quantity-"]').fill('2');
 await page.getByRole('button',{name:'Confirm restock',exact:true}).click();await page.locator('dialog').waitFor({state:'hidden'});
 const after=await page.evaluate(()=>JSON.parse(localStorage.getItem('pantry-organizer.demo.v1')).state);
 const blueberryId=before.products.find(p=>p.name==='Blueberries').id;assert.deepEqual(after.batches.filter(b=>b.productId===blueberryId),before.batches.filter(b=>b.productId===blueberryId));
 assert.match(await page.locator('.card').filter({has:page.getByRole('heading',{name:'Rice',exact:true})}).innerText(),/Full/);
 assert.match(await page.locator('.card').filter({has:page.getByRole('heading',{name:'Avocados',exact:true})}).locator('.amount').innerText(),/6 items/);pass('bulk restock saves selected, individually adjusted foods and leaves others untouched');
 const checked=after.batches.map(b=>b.checkedAt);await page.reload();await page.locator('.card').first().waitFor();assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('pantry-organizer.demo.v1')).state.batches.map(b=>b.checkedAt)),checked);pass('opening inventory does not mark foods freshly checked');
 await page.getByRole('button',{name:/Running low/}).click();assert.equal(await page.locator('.card').count(),1);pass('visible low-stock summary filters to remaining low food');
 await page.getByRole('button',{name:/Use soon/}).click();assert.ok(await page.locator('.card').count()>0);pass('optional expiry summary finds upcoming package dates');
 await page.getByRole('button',{name:/Foods at home/}).click();
 const staleCard=page.locator('.card').filter({has:page.getByRole('heading',{name:'Rice',exact:true})});await staleCard.getByRole('button',{name:'Update Rice batch'}).click();await page.locator('select[name="quantity"]').selectOption('0.25');
 const second=await page.context().newPage();await second.goto('http://localhost:4173');const secondCard=second.locator('.card').filter({has:second.getByRole('heading',{name:'Rice',exact:true})});await secondCard.getByRole('button',{name:'Update Rice batch'}).click();await second.locator('select[name="quantity"]').selectOption('0.5');await second.getByRole('button',{name:'Save update',exact:true}).click();await second.locator('dialog').waitFor({state:'hidden'});
 await page.getByRole('button',{name:'Save update',exact:true}).click();assert.match(await page.locator('dialog .error').innerText(),/Stock changed/);const savedLevel=await page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('pantry-organizer.demo.v1')).state;return s.batches.find(b=>b.productId===s.products.find(p=>p.name==='Rice').id).quantity;});assert.equal(savedLevel,0.5);await page.getByRole('button',{name:'Cancel',exact:true}).click();await second.close();pass('stale open form cannot overwrite another tab’s stock check');
 const riceCard=page.locator('.card').filter({has:page.getByRole('heading',{name:'Rice',exact:true})});await riceCard.getByRole('button',{name:/To list/}).click();await page.getByRole('button',{name:/Shopping list/}).click();let riceRow=page.locator('.shopping-row').filter({has:page.getByRole('heading',{name:'Rice',exact:true})});await riceRow.waitFor();const beforeDelete=await page.evaluate(()=>JSON.parse(localStorage.getItem('pantry-organizer.demo.v1')).state);const riceId=beforeDelete.products.find(p=>p.name==='Rice').id;
 await page.getByRole('button',{name:'My inventory'}).click();await page.locator('.card').filter({has:page.getByRole('heading',{name:'Rice',exact:true})}).getByRole('button',{name:'Delete Rice'}).click();await page.getByRole('heading',{name:'Delete Rice?'}).waitFor();assert.match(await page.locator('dialog').innerText(),/stock batches, activity history, and shopping-list entries/);await page.getByRole('button',{name:'Cancel',exact:true}).click();await page.locator('dialog').waitFor({state:'hidden'});assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('pantry-organizer.demo.v1')).state),beforeDelete);pass('canceling food deletion preserves pantry and linked shopping state');
 await page.locator('.card').filter({has:page.getByRole('heading',{name:'Rice',exact:true})}).getByRole('button',{name:'Delete Rice'}).click();await page.getByRole('button',{name:'Delete food'}).click();await page.locator('dialog').waitFor({state:'hidden'});assert.equal(await page.locator('.card').filter({has:page.getByRole('heading',{name:'Rice',exact:true})}).count(),0);const deletedState=await page.evaluate(()=>JSON.parse(localStorage.getItem('pantry-organizer.demo.v1')).state);assert.equal(deletedState.products.some(p=>p.id===riceId),false);assert.equal(deletedState.batches.some(b=>b.productId===riceId),false);assert.equal(deletedState.movements.some(m=>m.productId===riceId),false);assert.equal(deletedState.shopping.some(i=>i.productId===riceId),false);assert.ok(deletedState.products.some(p=>p.name==='Avocados'));pass('confirmed food deletion removes only the selected food and dependent data');
 await page.getByRole('button',{name:/Shopping list/}).click();assert.equal(await page.locator('.shopping-row').filter({has:page.getByRole('heading',{name:'Rice',exact:true})}).count(),0);pass('deleted food is removed from the shopping list');
 await page.setViewportSize({width:1280,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);pass('desktop layout has no horizontal overflow');
 await page.getByRole('button',{name:'Connect',exact:true}).click();await page.getByRole('heading',{name:'Connect your shared pantry'}).waitFor();pass('missing backend configuration is clearly explained');
 assert.deepEqual(errors,[]);pass('no browser runtime errors');
}finally{await browser.close();}
