import React, { useState } from 'react';
import { categories, type PantryItem } from './types.ts';
import { AddButton, AmountLabel, EmptyState, Icon, SearchBox, StatusPill, type VariantProps } from './ui.tsx';

export const VariantF: React.FC<VariantProps> = ({ items, filtered, search, category, lowOnly, onSearch, onCategory, onLowOnly, onAdd, onRestock, onUse }) => {
  const [selectedId, setSelectedId] = useState(items[0]?.id ?? '');
  const selected = filtered.find((item) => item.id === selectedId) ?? filtered[0];
  const groups = categories.filter((name) => items.some((item) => item.category === name));
  return <main className="variant-f">
    <header className="f-header"><div className="f-logo"><span className="f-logo-icon"><Icon name="brand" size={19} /></span><span>pantry<span>HOUSEHOLD INVENTORY / 01</span></span></div><div className="f-header-state"><i /> LOCAL SAMPLE REGISTER</div><AddButton onClick={onAdd} label="New item" /></header>
    <section className="f-title-row"><div><span className="f-kicker">HOUSEHOLD STOCK REGISTER</span><h1>Inventory <span>/{items.length.toString().padStart(2, '0')}</span></h1><p>Every item has a place, a count, and a next action.</p></div><div className="f-ledger-stats"><div><span>ITEMS ON FILE</span><strong>{items.length.toString().padStart(2, '0')}</strong></div><div><span>NEED ATTENTION</span><strong>{items.filter((item) => item.level !== 'ready').length.toString().padStart(2, '0')}</strong></div></div></section>
    <section className="f-toolbar"><SearchBox value={search} onChange={onSearch} placeholder="Search the register" /><label className="f-select"><span>Category</span><select aria-label="Filter by category" value={category} onChange={(event) => onCategory(event.currentTarget.value)}><option value="all">All categories</option>{groups.map((name) => <option key={name}>{name}</option>)}</select></label><button className={`f-attention ${lowOnly ? 'active' : ''}`} type="button" aria-pressed={lowOnly} onClick={onLowOnly}><i />Needs attention</button><span className="f-record-count">{filtered.length.toString().padStart(2, '0')} RECORDS</span></section>
    <section className="f-register"><div className="f-index-panel"><div className="f-index-head"><span>ITEM / CATEGORY</span><span>STOCK</span><span>AMOUNT</span></div>{filtered.length ? filtered.map((item: PantryItem, index) => <button type="button" key={item.id} className={`f-record ${selected?.id === item.id ? 'selected' : ''}`} aria-pressed={selected?.id === item.id} onClick={() => setSelectedId(item.id)}><span className="f-row-no">{(index + 1).toString().padStart(2, '0')}</span><span className="f-record-main"><strong>{item.name}</strong><small>{item.category}</small></span><span className={`f-level ${item.level}`}>{item.level === 'ready' ? 'READY' : item.level === 'low' ? 'LOW' : 'OUT'}</span><span className="f-record-amount">{item.amount}<small>{item.unit}</small></span></button>) : <EmptyState />}</div>
      {selected ? <aside className="f-detail"><div className="f-detail-top"><span>SELECTED RECORD</span><span>{selected.id.slice(-4).toUpperCase()}</span></div><div className="f-detail-title"><span className="f-item-glyph"><Icon name="box" size={22} /></span><div><span className="f-kicker">ITEM DETAILS</span><h2>{selected.name}</h2></div></div><StatusPill item={selected} /><div className="f-detail-count"><div><span>ON HAND</span><strong>{selected.amount.toString().padStart(2, '0')} <small>{selected.unit}</small></strong></div><div><span>STORED IN</span><strong>{selected.location}</strong></div></div><dl className="f-properties"><div><dt>Category</dt><dd>{selected.category}</dd></div><div><dt>Stock status</dt><dd>{selected.level === 'ready' ? 'Ready to use' : selected.level === 'low' ? 'Running low' : 'Out of stock'}</dd></div><div><dt>Household record</dt><dd>Illustrative only</dd></div></dl><div className="f-detail-actions"><button type="button" className="f-use" onClick={() => onUse(selected.id)}><Icon name="minus" size={16} />Use one</button><button type="button" className="f-restock" onClick={() => onRestock(selected.id)}><Icon name="plus" size={16} />Restock one</button></div><p>Sample changes live only in this tab.</p></aside> : <aside className="f-detail f-empty-detail"><span className="f-item-glyph"><Icon name="box" /></span><strong>Select an item to inspect its record.</strong></aside>}</section>
    <footer className="f-footer"><span>REGISTER NO. 01 · SAMPLE DATA</span><span>Stock figures are illustrative, not saved</span></footer>
  </main>;
};
