import React from 'react';
import { categories, type PantryItem } from './types.ts';
import { AddButton, AmountLabel, EmptyState, Icon, SearchBox, StatusPill, type VariantProps } from './ui.tsx';

export const VariantE: React.FC<VariantProps> = ({ items, filtered, search, category, lowOnly, onSearch, onCategory, onLowOnly, onAdd, onRestock, onUse }) => {
  const counted = categories.map((name) => ({ name, count: items.filter((item) => item.category === name).length })).filter((entry) => entry.count > 0);
  const checkSoon = items.filter((item) => item.level !== 'ready');
  return <main className="variant-e">
    <header className="e-header"><div className="e-logo"><span className="e-logo-mark"><Icon name="brand" size={20} /></span><span>pantry<small>easy does it.</small></span></div><span className="e-household">A LITTLE HOME, WELL STOCKED <i /></span><AddButton onClick={onAdd} label="Add to pantry" /></header>
    <section className="e-intro"><div><span className="e-kicker">GOOD MORNING, HOME COOK</span><h1>What feels good<br />to make today?</h1><p>Take a gentle look around. The good things are already here.</p></div><div className="e-weather-card"><span className="e-weather-mark"><Icon name="spark" size={22} /></span><div><small>YOUR PANTRY CHECK-IN</small><strong>{checkSoon.length ? `${checkSoon.length} things could use a look` : 'Everything is in good shape'}</strong><span>{items.length} familiar foods, all in one place</span></div></div></section>
    <section className="e-category-section"><div className="e-heading"><span className="e-kicker">FIND YOUR WAY</span><h2>Browse by shelf</h2></div><div className="e-category-grid"><button type="button" className={`e-category-tile all ${category === 'all' ? 'selected' : ''}`} onClick={() => onCategory('all')}><span className="e-tile-icon"><Icon name="box" /></span><strong>Everything</strong><small>{items.length} foods</small></button>{counted.map((entry, index) => <button type="button" key={entry.name} className={`e-category-tile tone-${index % 4} ${category === entry.name ? 'selected' : ''}`} aria-pressed={category === entry.name} onClick={() => onCategory(category === entry.name ? 'all' : entry.name)}><span className="e-tile-icon"><Icon name={index % 2 ? 'spark' : 'box'} /></span><strong>{entry.name}</strong><small>{entry.count} {entry.count === 1 ? 'food' : 'foods'}</small></button>)}</div></section>
    <section className="e-main-grid"><div className="e-list-panel"><div className="e-heading e-list-heading"><div><span className="e-kicker">THE EVERYDAY COLLECTION</span><h2>{category === 'all' ? 'A little of everything' : category}</h2></div><span className="e-count">{filtered.length} foods</span></div><div className="e-tools"><SearchBox value={search} onChange={onSearch} placeholder="Find a food" /><button type="button" className={`e-low-filter ${lowOnly ? 'selected' : ''}`} aria-pressed={lowOnly} onClick={onLowOnly}><span />Low or empty</button></div>{filtered.length ? <div className="e-food-list">{filtered.map((item: PantryItem) => <article className="e-food-row" key={item.id}><span className={`e-food-dot ${item.level}`} /><div className="e-food-name"><strong>{item.name}</strong><small>{item.category} · {item.location}</small></div><StatusPill item={item} /><AmountLabel item={item} /><div className="e-row-actions"><button type="button" aria-label={`Use one ${item.name}`} title="Use one" onClick={() => onUse(item.id)}><Icon name="minus" size={16} /></button><button type="button" aria-label={`Restock ${item.name}`} title="Add one" onClick={() => onRestock(item.id)}><Icon name="plus" size={16} /></button></div></article>)}</div> : <EmptyState />}</div>
      <aside className="e-check-panel"><div className="e-check-heading"><span className="e-check-icon"><Icon name="check" size={19} /></span><div><span className="e-kicker">A QUICK CHECK</span><h3>Almost out</h3></div><b>{checkSoon.length.toString().padStart(2, '0')}</b></div><p>These are the ones to peek at before your next shop.</p>{checkSoon.slice(0, 6).map((item) => <div className="e-check-item" key={item.id}><div><strong>{item.name}</strong><small>{item.level === 'out' ? 'Empty' : 'Running low'}</small></div><button type="button" aria-label={`Restock ${item.name}`} onClick={() => onRestock(item.id)}><Icon name="plus" size={16} /></button></div>)}<div className="e-check-footer"><span>Small check-ins make for easier meals.</span><Icon name="spark" size={16} /></div></aside></section>
    <footer className="e-footer"><span>pantry, a little less waste.</span><span>This is a local design sample. Nothing is saved.</span></footer>
  </main>;
};
