import React from 'react';
import type { PantryItem } from './types.ts';
import { AddButton, AmountLabel, Brand, EmptyState, Filters, Icon, StatusPill, type VariantProps } from './ui.tsx';

export const VariantC: React.FC<VariantProps> = ({ filtered, search, category, lowOnly, tripIds, onSearch, onCategory, onLowOnly, onAdd, onRestock, onUse, onToggleTrip }) => {
  const needsAttention = filtered.filter((item) => item.level !== 'ready');
  const ready = filtered.filter((item) => item.level === 'ready');
  return <main className="variant-c">
    <header className="c-topbar"><Brand /><span className="sample-ribbon"><span />Sample pantry · illustrative stock</span><span className="c-date">SUNDAY · HOME CHECK-IN</span></header>
    <section className="c-hero"><div className="c-hero-copy"><span className="eyebrow">BEFORE THE NEXT SHOP</span><h1>Make the most<br />of what’s here.</h1><p>A quick stock check helps you plan a better grocery trip.</p><div className="c-hero-stats"><span><b>{needsAttention.length}</b> to check</span><span><b>{tripIds.length}</b> on your list</span></div></div><div className="c-hero-action"><div className="c-route-icon"><Icon name="arrow" size={28} /></div><span className="eyebrow">YOUR NEXT STEP</span><strong>{needsAttention.length ? 'Check the low items first' : 'Your pantry looks ready'}</strong><span>Each change is local to this demo.</span><AddButton onClick={onAdd} label="Add a food" /></div></section>
    <section className="c-planner"><div className="c-plan-heading"><div><span className="eyebrow">GROCERY TRIP PLANNER</span><h2>Start with what needs attention</h2></div><span className="c-trip-count">{tripIds.length} selected for the trip</span></div><Filters search={search} category={category} lowOnly={lowOnly} onSearch={onSearch} onCategory={onCategory} onLowOnly={onLowOnly} />
      {filtered.length === 0 ? <EmptyState /> : <div className="c-columns"><section className="c-need-list"><div className="c-list-title"><span className="c-number">01</span><div><h3>Check & decide</h3><p>Low and empty foods, first.</p></div><b>{needsAttention.length}</b></div>{needsAttention.length ? needsAttention.map((item: PantryItem) => <article className="c-task-row" key={item.id}><button type="button" className={`trip-checkbox ${tripIds.includes(item.id) ? 'checked' : ''}`} aria-label={`${tripIds.includes(item.id) ? 'Remove' : 'Add'} ${item.name} ${tripIds.includes(item.id) ? 'from' : 'to'} grocery list`} aria-pressed={tripIds.includes(item.id)} onClick={() => onToggleTrip(item.id)}>{tripIds.includes(item.id) && <Icon name="check" size={14} />}</button><div className="c-task-copy"><strong>{item.name}</strong><span>{item.category}</span></div><div className="c-task-stock"><StatusPill item={item} /><AmountLabel item={item} /></div><button type="button" className="check-in-button" onClick={() => onUse(item.id)}>Check in</button><button type="button" className="c-add-stock" aria-label={`Restock ${item.name}`} title="Restock locally" onClick={() => onRestock(item.id)}><Icon name="plus" /></button></article>) : <div className="c-all-good"><span><Icon name="check" /></span><div><strong>Nothing urgent right now</strong><small>Use the pantry list to plan ahead.</small></div></div>}</section>
        <section className="c-ready-list"><div className="c-list-title"><span className="c-number calm">02</span><div><h3>Already on hand</h3><p>Keep these in mind while shopping.</p></div><b>{ready.length}</b></div>{ready.slice(0, 9).map((item: PantryItem) => <article className="c-ready-row" key={item.id}><span className="ready-marker" /><div><strong>{item.name}</strong><small>{item.category}</small></div><AmountLabel item={item} /><button type="button" className="trip-add-small" aria-label={`${tripIds.includes(item.id) ? 'Remove from' : 'Add to'} grocery list: ${item.name}`} aria-pressed={tripIds.includes(item.id)} onClick={() => onToggleTrip(item.id)}>{tripIds.includes(item.id) ? <Icon name="check" size={16} /> : <Icon name="plus" size={16} />}</button></article>)}{ready.length > 9 && <span className="c-more">+ {ready.length - 9} more foods in your pantry</span>}</section></div>}
    </section>
    <footer className="c-footnote"><span><Icon name="spark" size={16} /> Sample data only</span><span>Changes stay in memory and disappear when this tab closes.</span></footer>
  </main>;
};
