import React from 'react';
import { categories, type PantryItem } from './types.ts';
import { AddButton, AmountLabel, EmptyState, Icon, SearchBox, StatusPill, type VariantProps } from './ui.tsx';

export const VariantB: React.FC<VariantProps> = ({ items, filtered, search, category, lowOnly, onSearch, onCategory, onLowOnly, onAdd, onRestock, onUse }) => {
  const countFor = (value: string) => items.filter((item) => value === 'all' ? true : item.category === value).length;
  return <main className="variant-b">
    <aside className="b-sidebar"><div className="b-brand"><span className="b-brand-mark"><Icon name="brand" size={21} /></span><div>pantry<small>HOUSEHOLD INVENTORY</small></div></div><span className="b-nav-label">WORKSPACE</span><button type="button" className="b-nav-item active"><span>▤</span>Inventory <b>{items.length}</b></button><button type="button" className="b-nav-item"><span>✓</span>Shopping list <b>0</b></button><button type="button" className="b-nav-item"><span>◷</span>Activity</button><div className="b-side-divider" /><span className="b-nav-label">CATEGORIES</span><button type="button" className={`b-category ${category === 'all' ? 'selected' : ''}`} onClick={() => onCategory('all')}><span className="category-dot all" />All foods <small>{items.length}</small></button>{categories.filter((value) => countFor(value)).map((value) => <button type="button" key={value} className={`b-category ${category === value ? 'selected' : ''}`} onClick={() => onCategory(category === value ? 'all' : value)}><span className="category-dot" />{value}<small>{countFor(value)}</small></button>)}<div className="b-sidebar-foot"><span className="demo-avatar">M</span><div><b>Sample household</b><small>Local prototype</small></div><span className="online-dot" /></div></aside>
    <section className="b-main"><header className="b-topbar"><div><span className="eyebrow">PANTRY / INVENTORY</span><h1>Inventory workspace</h1></div><AddButton onClick={onAdd} /></header><div className="b-meta-row"><span><i className="live-dot" /> SAMPLE DATA</span><span>Last checked just now · illustrative only</span></div><div className="b-kpis"><div><span>ALL FOODS</span><strong>{items.length}</strong><small>Across all categories</small></div><div><span>LOW / OUT</span><strong>{items.filter((item) => item.level !== 'ready').length}</strong><small>Worth a quick check</small></div><div><span>CATEGORIES</span><strong>{new Set(items.map((item) => item.category)).size}</strong><small>Organized for this home</small></div></div>
      <div className="b-toolbar"><SearchBox value={search} onChange={onSearch} placeholder="Search inventory…" /><button type="button" className={`toggle-filter ${lowOnly ? 'is-active' : ''}`} aria-pressed={lowOnly} onClick={onLowOnly}><span className="toggle-dot" />Low / out</button><span className="b-result-count">{filtered.length} foods</span></div>
      {filtered.length === 0 ? <EmptyState /> : <div className="inventory-table-wrap"><table className="inventory-table"><thead><tr><th>FOOD</th><th>CATEGORY</th><th>LOCATION</th><th>STATUS</th><th>ON HAND</th><th>ADJUST</th></tr></thead><tbody>{filtered.map((item: PantryItem) => <tr key={item.id}><td><div className="b-food-cell"><span className="food-mini"><Icon name="box" size={16} /></span><b>{item.name}</b></div></td><td><button type="button" className="table-category" onClick={() => onCategory(item.category)}>{item.category}</button></td><td>{item.location}</td><td><StatusPill item={item} /></td><td><AmountLabel item={item} /></td><td><div className="table-adjust"><button type="button" aria-label={`Use one ${item.name}`} onClick={() => onUse(item.id)}><Icon name="minus" size={16} /></button><button type="button" aria-label={`Restock ${item.name}`} onClick={() => onRestock(item.id)}><Icon name="plus" size={16} /></button></div></td></tr>)}</tbody></table></div>}
      <footer className="b-footnote">Prototype data is local to this tab. No household or cloud data is connected.</footer>
    </section>
  </main>;
};
